[project]
name = "anthropic-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.42.0",
    "inquirer>=3.4.0",
    "prompt-toolkit>=3.0.48",
    "python-dotenv>=1.0.1",
    "rich>=13.9.4",
]
